name: Update Repository Automatically

on:
  push:
    branches:
      - master  # atau ganti dengan main jika itu nama branch Anda

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run update commands
        run: |
          git add .
          git commit -m "Automatic update" || echo "No changes to commit"
          git push origin master  # pastikan branch sesuai dengan branch di atas

